### ISSUE TITLE
WelcomeScreen - only one button to navigate to get user info screen

### ISSUE THREAD

**Issue by hyunjiLeeTech** [1B2K/HealthGuard#1]
Now we have two buttons  - log in and create account

Following the meeting we discussed about the application structure, erase one button and keep one. Name it to 'Start HealthGuard' (you can name it) and make it navigate to GetUserInfoScreen

**Comment by hyunjiLeeTech** [comment]
Use color - lightBlue_button for button color. It's inside colors.js file (/src/config/colors.js). You can see other files' code as a reference

**Comment by HyoukSunKwon** [comment]
Change button: before - two buttons to signup and login 
                          after - one button for start

change button color: before - dark blue
                                   after - light blue

**Comment by hyunjiLeeTech** [comment]
Please create a pull request so we can review your code :) (or we can discuss about this on Friday meeting)

**Comment by hyunjiLeeTech** [comment]
Closed by 5ec938a490a364bd1105dcb57b6c2e60d41aa682
