### ISSUE TITLE
Update authentication 

### ISSUE THREAD

**Issue by ElisaNgLi** [1B2K/HealthGuard#23]
Modify current Sign in, sign-up, signout authentication to fit the new model.

1. Display welcome screen to the app
2.  Ask for DOB and gender
3. Display home screen

No need to create an account.

**Comment by ElisaNgLi** [comment]
We do not need to modify our current authentication to fit the new model since It is already doing what is supposed to with the dummy data. 
Please check this matter @hyunjiLeeTech  @HyoukSunKwon 
If you girls think we need to add another layer of authentication please let me know. Since another issue about the Signout is created we can modify that part once is time to work on that issue... Other than that I think the current authentication still fits our current model.

**Comment by hyunjiLeeTech** [comment]
I think so too. We can keep this model until other authentications need in the future.

**Comment by ElisaNgLi** [comment]
For version 1 we do not need to update the current authentication.
