### ISSUE TITLE
ProfileScreen - Update fields to match AddAccountScreen

### ISSUE THREAD

**Issue by ElisaNgLi** [1B2K/HealthGuard#3]
Change Date of birth and Gender field to match AddAccountScreen 
Follow the format of GetUserInfoScreen
1. DOB
- Day: DropDownPicker with 1-31
- Month: DropDownPicker with Jan-Dec
- Year: DropDownPicker with 1920-current year

2. Gender
- DropDownPicker with male, female, other (maybe we can add more)

Update functionality of the buttons such as edit

**Comment by hyunjiLeeTech** [comment]
I'm going to change the value of monArr. The 'value:1' will be changed to 'value:"January"'. I've created an issue related to this #14 . You can check it as a reference.

**Comment by ElisaNgLi** [comment]
Close by 1e61e1b1571039fb2423eda83775b5659d161f2d
