### ISSUE TITLE
AddVaccinationHistoryScreen - Change the field type for vaccine type

### ISSUE THREAD

**Issue by HyoukSunKwon** [1B2K/HealthGuard#54]
1. need to organize the vaccine category and range of vaccination.
2. do we need a "user typable section"  for add vaccination history?

**Comment by hyunjiLeeTech** [comment]
1. Create another DropDownPicker about category
2. When user choose the category, display vaccine types related to that category

**Comment by hyunjiLeeTech** [comment]
Following March 19th meeting, we can work it on issue #38
