### ISSUE TITLE
GetUserInfoScreen - Set up backend (AsyncStorage) to store the input data into storage

### ISSUE THREAD

**Issue by hyunjiLeeTech** [1B2K/HealthGuard#60]

**Comment by ElisaNgLi** [comment]
Refer to the following links for more information on how to implement this: 
 https://reactnative.dev/docs/asyncstorage 
https://www.reactnativeschool.com/migrating-data-in-asyncstorage
https://heartbeat.fritz.ai/building-offline-react-native-apps-with-asyncstorage-dcb4b0657f93

**Comment by ElisaNgLi** [comment]
Database MongoDB documentation:
https://docs.mongodb.com/realm/tutorial/react-native/
https://docs.mongodb.com/realm/react-native/
